# GitHub Pages 配置
title: "AIOGEO 知識庫"
description: "專業的 GEO (Generative Engine Optimization) 知識庫"
url: "https://geo.25min.co"
baseurl: ""

# 作者資訊
author:
  name: "廖天佑 Bless Liao"
  github: "bless25min"

# 網站基本設定
lang: zh-TW
timezone: Asia/Taipei

# 插件配置（簡化版，避免部署錯誤）
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag

# 排除檔案
exclude:
  - node_modules/
  - .git/
  - .gitignore
  - .github/
  - vendor/
  - Gemfile
  - Gemfile.lock

# Markdown 處理器
markdown: kramdown
highlighter: rouge

# 基本設定
kramdown:
  input: GFM
  hard_wrap: false

# SEO 設定
social:
  name: 廖天佑 Bless Liao
  links:
    - https://github.com/bless25min
    - https://geo.25min.co

# 預設值
defaults:
  - scope:
      path: ""
    values:
      author: "廖天佑 Bless Liao"
