name: 🔄 Path Update Solution - Convert All Links to Static HTML

on:
  workflow_dispatch:
    inputs:
      update_scope:
        description: '更新範圍'
        required: false
        default: 'all'
        type: choice
        options:
        - all
        - navigation_only
        - content_only

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  update-all-paths:
    runs-on: ubuntu-latest
    
    steps:
    - name: 🔄 Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: 🛠️ Configure Git safely
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "AIOGEO Path Updater"
        git config pull.rebase false
        git fetch origin main
        git reset --hard origin/main

    - name: 📋 Update _sidebar.md navigation
      run: |
        echo "📋 更新側邊欄導航連結..."
        
        cat > _sidebar.md << 'EOF'
        <!-- AIOGEO 知識庫導航結構 -->
        
        ## 🏠 [首頁](/)
        
        ## 👤 關於專案
        - [關於作者](about.html)
        - [參與貢獻](contributing.html)
        - [隱私政策](privacy.html)
        
        ## 📚 理論基礎
        - [GEO 基礎原理](geo-fundamentals.html)
        - [AI 搜尋演算法解析](ai-search-algorithm.html)
        - [答案層設計指南](answer-layer-design.html)
        - [語意錨定技術](semantic-anchoring.html)
        - [語意網格架構](semantic-mesh.html)
        
        ## 🎯 優化策略
        - [SEO 與 GEO 整合](seo-geo-integration.html)
        - [引用增強策略](citation-enhancement.html)
        - [FAQ 設計原則](faq-design.html)
        - [Schema 實作指南](schema-implementation.html)
        
        ## 🔬 前沿技術
        - [多模態內容優化](multimodal-optimization.html)
        - [多模態創作指南](multimodal-creation.html)
        - [AI 引用追蹤](ai-citation-tracking.html)
        - [GEO 測量方法](geo-measurement.html)
        
        ## 🛠️ 實用工具
        - [工具總覽](tools-README.html)
        - [評估工具](tools-assessment-tools.html)
        - [檢查清單](tools-checklists.html)
        - [內容模板](tools-content-templates.html)
        - [Schema 生成器](tools-schema-generator.html)
        
        ## 📊 索引目錄
        - [GEO 基礎索引](geo-fundamentals-index.html)
        - [GEO 總覽](geo-fundamentals-overview.html)
        - [GEO 內容設計](geo-fundamentals-content-design.html)
        - [GEO 技術實作](geo-fundamentals-technical.html)
        - [GEO 測量](geo-fundamentals-measurement.html)
        
        ---
        
        ### 🔗 外部連結
        - [GitHub Repository](https://github.com/bless25min/AIOGEO-Knowledge)
        - [問題回報](https://github.com/bless25min/AIOGEO-Knowledge/issues)
        - [討論區](https://github.com/bless25min/AIOGEO-Knowledge/discussions)
        
        ---
        
        <div style="text-align: center; margin-top: 20px; padding: 15px; background: #f8fafc; border-radius: 8px;">
          <small style="color: #6b7280;">
            📚 <strong>AIOGEO 知識庫</strong><br>
            讓 AI 看見你的內容<br>
            作者：<a href="about.html">廖天佑 Bless</a>
          </small>
        </div>
        EOF

    - name: 📝 Update index.html navigation links
      run: |
        echo "📝 更新 index.html 中的導航連結..."
        
        # 備份原檔案
        cp index.html index.html.backup
        
        # 使用 sed 批量替換 hash 連結為 HTML 連結
        sed -i 's|href="#/about"|href="about.html"|g' index.html
        sed -i 's|href="#/contributing"|href="contributing.html"|g' index.html
        sed -i 's|href="#/privacy"|href="privacy.html"|g' index.html
        sed -i 's|href="#/posts/|href="|g' index.html
        sed -i 's|href="#/tools/|href="tools-|g' index.html
        
        # 修正特定的導航連結
        sed -i 's|<a href="#/" class="nav-link">|<a href="/" class="nav-link">|g' index.html
        sed -i 's|<a href="#/about" class="nav-link">|<a href="about.html" class="nav-link">|g' index.html
        sed -i 's|<a href="#/contributing" class="nav-link">|<a href="contributing.html" class="nav-link">|g' index.html
        
        echo "✅ index.html 連結更新完成"

    - name: 📄 Update README.md internal links
      run: |
        echo "📄 更新 README.md 中的內部連結..."
        
        if [ -f "README.md" ]; then
          # 備份原檔案
          cp README.md README.md.backup
          
          # 替換內部連結
          sed -i 's|\[關於作者\](#/about)|\[關於作者\](about.html)|g' README.md
          sed -i 's|\[參與貢獻\](#/contributing)|\[參與貢獻\](contributing.html)|g' README.md
          sed -i 's|\[GEO 基礎原理\](#/posts/geo-fundamentals)|\[GEO 基礎原理\](geo-fundamentals.html)|g' README.md
          sed -i 's|](#/posts/|](|g' README.md
          sed -i 's|](#/tools/|](tools-|g' README.md
          
          echo "✅ README.md 連結更新完成"
        fi

    - name: 📝 Update all markdown files internal links
      run: |
        echo "📝 更新所有 Markdown 檔案中的內部連結..."
        
        # 更新 posts 目錄下的所有 markdown 檔案
        if [ -d "posts" ]; then
          for file in posts/*.md; do
            if [ -f "$file" ]; then
              echo "  更新 $file..."
              # 備份
              cp "$file" "$file.backup"
              
              # 替換連結
              sed -i 's|\[返回首頁\](#/)|\[返回首頁\](/)|g' "$file"
              sed -i 's|\[關於作者\](#/about)|\[關於作者\](../about.html)|g' "$file"
              sed -i 's|\[參與貢獻\](#/contributing)|\[參與貢獻\](../contributing.html)|g' "$file"
              sed -i 's|](#/posts/|](|g' "$file"
              sed -i 's|](#/tools/|](../tools-|g' "$file"
              sed -i 's|\.md)|\.html)|g' "$file"
            fi
          done
        fi
        
        # 更新 tools 目錄下的所有 markdown 檔案
        if [ -d "tools" ]; then
          for file in tools/*.md; do
            if [ -f "$file" ]; then
              echo "  更新 $file..."
              # 備份
              cp "$file" "$file.backup"
              
              # 替換連結
              sed -i 's|\[返回首頁\](#/)|\[返回首頁\](/)|g' "$file"
              sed -i 's|\[關於作者\](#/about)|\[關於作者\](../about.html)|g' "$file"
              sed -i 's|\[參與貢獻\](#/contributing)|\[參與貢獻\](../contributing.html)|g' "$file"
              sed -i 's|](#/posts/|](../|g' "$file"
              sed -i 's|](#/tools/|](../tools-|g' "$file"
              sed -i 's|\.md)|\.html)|g' "$file"
            fi
          done
        fi
        
        # 更新根目錄的 about.md 和 contributing.md
        for file in about.md contributing.md privacy.md; do
          if [ -f "$file" ]; then
            echo "  更新 $file..."
            cp "$file" "$file.backup"
            sed -i 's|\[返回首頁\](#/)|\[返回首頁\](/)|g' "$file"
            sed -i 's|](#/posts/|](|g' "$file"
            sed -i 's|](#/tools/|](tools-|g' "$file"
            sed -i 's|\.md)|\.html)|g' "$file"
          fi
        done

    - name: 🗺️ Update sitemap.xml with all HTML pages
      run: |
        echo "🗺️ 更新 sitemap.xml 包含所有 HTML 頁面..."
        
        cat > sitemap.xml << 'SITEMAP_EOF'
        <?xml version="1.0" encoding="UTF-8"?>
        <urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
            <!-- 主頁面 -->
            <url>
                <loc>https://bless25min.github.io/AIOGEO-Knowledge/</loc>
                <lastmod>2025-07-08</lastmod>
                <changefreq>weekly</changefreq>
                <priority>1.0</priority>
            </url>
            
            <!-- 核心頁面 -->
            <url>
                <loc>https://bless25min.github.io/AIOGEO-Knowledge/about.html</loc>
                <lastmod>2025-07-08</lastmod>
                <changefreq>monthly</changefreq>
                <priority>0.8</priority>
            </url>
            <url>
                <loc>https://bless25min.github.io/AIOGEO-Knowledge/contributing.html</loc>
                <lastmod>2025-07-08</lastmod>
                <changefreq>monthly</changefreq>
                <priority>0.6</priority>
            </url>
            <url>
                <loc>https://bless25min.github.io/AIOGEO-Knowledge/privacy.html</loc>
                <lastmod>2025-07-08</lastmod>
                <changefreq>yearly</changefreq>
                <priority>0.3</priority>
            </url>
            
            <!-- 理論基礎文章 -->
            <url>
                <loc>https://bless25min.github.io/AIOGEO-Knowledge/geo-fundamentals.html</loc>
                <lastmod>2025-07-08</lastmod>
                <changefreq>weekly</changefreq>
                <priority>0.9</priority>
            </url>
            <url>
                <loc>https://bless25min.github.io/AIOGEO-Knowledge/ai-search-algorithm.html</loc>
                <lastmod>2025-07-08</lastmod>
                <changefreq>weekly</changefreq>
                <priority>0.8</priority>
            </url>
            <url>
                <loc>https://bless25min.github.io/AIOGEO-Knowledge/answer-layer-design.html</loc>
                <lastmod>2025-07-08</lastmod>
                <changefreq>weekly</changefreq>
                <priority>0.8</priority>
            </url>
            <url>
                <loc>https://bless25min.github.io/AIOGEO-Knowledge/semantic-anchoring.html</loc>
                <lastmod>2025-07-08</lastmod>
                <changefreq>weekly</changefreq>
                <priority>0.7</priority>
            </url>
            <url>
                <loc>https://bless25min.github.io/AIOGEO-Knowledge/semantic-mesh.html</loc>
                <lastmod>2025-07-08</lastmod>
                <changefreq>weekly</changefreq>
                <priority>0.7</priority>
            </url>
            
            <!-- 優化策略文章 -->
            <url>
                <loc>https://bless25min.github.io/AIOGEO-Knowledge/seo-geo-integration.html</loc>
                <lastmod>2025-07-08</lastmod>
                <changefreq>weekly</changefreq>
                <priority>0.8</priority>
            </url>
            <url>
                <loc>https://bless25min.github.io/AIOGEO-Knowledge/citation-enhancement.html</loc>
                <lastmod>2025-07-08</lastmod>
                <changefreq>weekly</changefreq>
                <priority>0.7</priority>
            </url>
            <url>
                <loc>https://bless25min.github.io/AIOGEO-Knowledge/faq-design.html</loc>
                <lastmod>2025-07-08</lastmod>
                <changefreq>weekly</changefreq>
                <priority>0.7</priority>
            </url>
            <url>
                <loc>https://bless25min.github.io/AIOGEO-Knowledge/schema-implementation.html</loc>
                <lastmod>2025-07-08</lastmod>
                <changefreq>weekly</changefreq>
                <priority>0.7</priority>
            </url>
            
            <!-- 前沿技術文章 -->
            <url>
                <loc>https://bless25min.github.io/AIOGEO-Knowledge/multimodal-optimization.html</loc>
                <lastmod>2025-07-08</lastmod>
                <changefreq>weekly</changefreq>
                <priority>0.7</priority>
            </url>
            <url>
                <loc>https://bless25min.github.io/AIOGEO-Knowledge/multimodal-creation.html</loc>
                <lastmod>2025-07-08</lastmod>
                <changefreq>weekly</changefreq>
                <priority>0.7</priority>
            </url>
            <url>
                <loc>https://bless25min.github.io/AIOGEO-Knowledge/ai-citation-tracking.html</loc>
                <lastmod>2025-07-08</lastmod>
                <changefreq>weekly</changefreq>
                <priority>0.7</priority>
            </url>
            <url>
                <loc>https://bless25min.github.io/AIOGEO-Knowledge/geo-measurement.html</loc>
                <lastmod>2025-07-08</lastmod>
                <changefreq>weekly</changefreq>
                <priority>0.7</priority>
            </url>
            
            <!-- 工具頁面 -->
            <url>
                <loc>https://bless25min.github.io/AIOGEO-Knowledge/tools-README.html</loc>
                <lastmod>2025-07-08</lastmod>
                <changefreq>monthly</changefreq>
                <priority>0.6</priority>
            </url>
            <url>
                <loc>https://bless25min.github.io/AIOGEO-Knowledge/tools-assessment-tools.html</loc>
                <lastmod>2025-07-08</lastmod>
                <changefreq>monthly</changefreq>
                <priority>0.5</priority>
            </url>
            <url>
                <loc>https://bless25min.github.io/AIOGEO-Knowledge/tools-checklists.html</loc>
                <lastmod>2025-07-08</lastmod>
                <changefreq>monthly</changefreq>
                <priority>0.6</priority>
            </url>
            <url>
                <loc>https://bless25min.github.io/AIOGEO-Knowledge/tools-content-templates.html</loc>
                <lastmod>2025-07-08</lastmod>
                <changefreq>monthly</changefreq>
                <priority>0.6</priority>
            </url>
            <url>
                <loc>https://bless25min.github.io/AIOGEO-Knowledge/tools-schema-generator.html</loc>
                <lastmod>2025-07-08</lastmod>
                <changefreq>monthly</changefreq>
                <priority>0.5</priority>
            </url>
            
            <!-- 索引頁面 -->
            <url>
                <loc>https://bless25min.github.io/AIOGEO-Knowledge/geo-fundamentals-index.html</loc>
                <lastmod>2025-07-08</lastmod>
                <changefreq>weekly</changefreq>
                <priority>0.6</priority>
            </url>
            <url>
                <loc>https://bless25min.github.io/AIOGEO-Knowledge/geo-fundamentals-overview.html</loc>
                <lastmod>2025-07-08</lastmod>
                <changefreq>weekly</changefreq>
                <priority>0.6</priority>
            </url>
            <url>
                <loc>https://bless25min.github.io/AIOGEO-Knowledge/geo-fundamentals-content-design.html</loc>
                <lastmod>2025-07-08</lastmod>
                <changefreq>weekly</changefreq>
                <priority>0.6</priority>
            </url>
            <url>
                <loc>https://bless25min.github.io/AIOGEO-Knowledge/geo-fundamentals-technical.html</loc>
                <lastmod>2025-07-08</lastmod>
                <changefreq>weekly</changefreq>
                <priority>0.6</priority>
            </url>
            <url>
                <loc>https://bless25min.github.io/AIOGEO-Knowledge/geo-fundamentals-measurement.html</loc>
                <lastmod>2025-07-08</lastmod>
                <changefreq>weekly</changefreq>
                <priority>0.6</priority>
            </url>
        </urlset>
        SITEMAP_EOF

    - name: 📊 Generate navigation report
      run: |
        echo "📊 生成導航更新報告..."
        
        echo "=== 導航連結更新報告 ===" > navigation-update-report.txt
        echo "更新時間: $(date)" >> navigation-update-report.txt
        echo "" >> navigation-update-report.txt
        
        echo "=== 主要更新項目 ===" >> navigation-update-report.txt
        echo "✅ _sidebar.md - 側邊欄導航連結" >> navigation-update-report.txt
        echo "✅ index.html - 主頁面導航連結" >> navigation-update-report.txt
        echo "✅ README.md - 首頁內部連結" >> navigation-update-report.txt
        echo "✅ posts/*.md - 所有文章內部連結" >> navigation-update-report.txt
        echo "✅ tools/*.md - 所有工具頁面內部連結" >> navigation-update-report.txt
        echo "✅ sitemap.xml - 完整站點地圖" >> navigation-update-report.txt
        echo "" >> navigation-update-report.txt
        
        echo "=== 連結格式變更 ===" >> navigation-update-report.txt
        echo "變更前: #/about → 變更後: about.html" >> navigation-update-report.txt
        echo "變更前: #/posts/article → 變更後: article.html" >> navigation-update-report.txt
        echo "變更前: #/tools/tool → 變更後: tools-tool.html" >> navigation-update-report.txt
        echo "" >> navigation-update-report.txt
        
        echo "=== 預期效果 ===" >> navigation-update-report.txt
        echo "📈 SEO 提升: 靜態 URL 對搜尋引擎更友善" >> navigation-update-report.txt
        echo "🤖 AI 引用: 靜態頁面更容易被 AI 理解和引用" >> navigation-update-report.txt
        echo "🚀 使用者體驗: 直接訪問特定頁面，無需載入 SPA" >> navigation-update-report.txt
        echo "📊 分析追蹤: 每個頁面都有獨立的 URL 便於分析" >> navigation-update-report.txt
        
        cat navigation-update-report.txt

    - name: 🚀 Commit all navigation updates
      run: |
        echo "🚀 提交所有導航更新..."
        
        # 檢查變更
        if [ -n "$(git status --porcelain)" ]; then
          echo "📝 發現檔案變更，準備提交..."
          
          # 添加所有變更的檔案
          git add .
          
          # 提交變更
          git commit -m "🔄 完整路徑更新：Hash → HTML靜態連結

          🎯 主要變更:
          ✅ _sidebar.md - 更新所有導航連結指向 HTML 頁面
          ✅ index.html - 修正頁面內導航連結
          ✅ README.md - 更新首頁內部連結
          ✅ posts/*.md - 批量更新文章內部連結  
          ✅ tools/*.md - 批量更新工具頁面連結
          ✅ sitemap.xml - 完整的靜態頁面站點地圖
          
          📊 改善效果:
          - 🔍 SEO 友善: 靜態 URL 易於搜尋引擎索引
          - 🤖 AI 引用: 提升 AI 平台的內容理解和引用
          - 🚀 使用者體驗: 直接訪問特定頁面
          - 📈 流量分析: 獨立 URL 便於追蹤分析
          
          🌐 連結格式統一:
          - Hash路由: #/page → 靜態頁面: page.html
          - 文章連結: #/posts/article → article.html  
          - 工具連結: #/tools/tool → tools-tool.html
          
          時間: $(date)"
          
          # 推送變更
          echo "📤 推送變更到遠端..."
          git push origin main --force-with-lease
          
          echo "✅ 所有導航更新已成功提交！"
        else
          echo "ℹ️ 沒有檔案需要更新"
        fi

    - name: 🎉 Update completion summary
      run: |
        echo "🎉 路徑更新完成！"
        echo ""
        echo "🔄 已完成的更新:"
        echo "  📋 側邊欄導航 (_sidebar.md)"
        echo "  🏠 主頁面連結 (index.html)"
        echo "  📄 首頁內容 (README.md)"
        echo "  📚 所有文章內部連結 (posts/*.md)"
        echo "  🛠️ 所有工具頁面連結 (tools/*.md)"
        echo "  🗺️ 站點地圖 (sitemap.xml)"
        echo ""
        echo "🎯 連結格式已統一:"
        echo "  ✅ 所有內部連結都指向 .html 靜態頁面"
        echo "  ✅ 移除了所有 # hash 路由格式"
        echo "  ✅ 保持了完整的導航功能"
        echo ""
        echo "📈 預期效果:"
        echo "  🔍 搜尋引擎更容易索引每個頁面"
        echo "  🤖 AI 平台更容易理解和引用內容"
        echo "  🚀 使用者可以直接訪問特定頁面"
        echo "  📊 每個頁面都有獨立的分析追蹤"
        echo ""
        echo "🌐 測試建議:"
        echo "  1. 等待 GitHub Pages 部署完成（3-5分鐘）"
        echo "  2. 測試側邊欄導航連結是否正常"
        echo "  3. 確認所有內部連結都能正確跳轉"
        echo "  4. 檢查 sitemap.xml 是否包含所有頁面"
        echo ""
        echo "🎊 恭喜！您的 AIOGEO 知識庫現在完全採用靜態頁面架構！"
